# action.yml3
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  etime: # id of output
    description: 'The time we greeted you'
  ls: # list the directory
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
  env:
    SOURCE_PATH: "/usr/local"